(* Title:      Kleene Algebra
   Author:     Alasdair Armstrong, Georg Struth, Tjark Weber
   Maintainer: Georg Struth <g.struth at sheffield.ac.uk>
               Tjark Weber <tjark.weber at it.uu.se>
*)

no_document use_thy "~~/src/HOL/Word/Word";

use_thys [
  "Signatures",
  "Dioid",
  "Dioid_Models",
  "Matrix",
  "Kleene_Algebra",
  "Kleene_Algebra_Models",
  "Action_Algebra",
  "Action_Algebra_Models",
  "Omega_Algebra",
  "Finite_Suprema",
  "Formal_Power_Series",
  "Inf_Matrix"
];
